#!/bin/bash
PARAMS=$@

#. `which hadoop` #>/dev/null #2>&1
# `which hadoop` #>/dev/null #2>&1
hadoop #>/dev/null #2>&1
echo "classpath=$CLASSPATH"
echo "ok = $HADOOP_LIBEXEC_DIR"

if [ "x$CLASSPATH" = "x" ]; then
    . $HADOOP_LIBEXEC_DIR/hadoop-config.sh
fi
#-----------
HAMSTER_CORE_BIN_FULLPATH=$(which hamster)
HAMSTER_CORE_HOME=${HAMSTER_CORE_BIN_FULLPATH%/*}

#CLASSPATH=$HADOOP_CONF_DIR:$YARN_CONF_DIR:$HDFS_CONF_DIR:$HAMSTER_CORE_HOME/../hamster-core-0.8.0/lib/hamster/*:$HAMSTER_CORE_HOME/../hamster-core-0.8.0/lib/hamster/lib/*:$HAMSTER_CORE_HOME/../hamster-core-0.8.0/conf:$CLASSPATH

CLASSPATH=$HAMSTER_CORE_HOME/../lib/hamster/*:$HAMSTER_CORE_HOME/../lib/hamster/lib/*:$HAMSTER_CORE_HOME/../conf:$CLASSPATH
#----------------
echo $CLASSPATH
java $JAVA_OPTS -cp $CLASSPATH com.pivotal.hamster.cli.HamsterCli $PARAMS