
™
!RefreshUserMappingsProtocol.protohadoop.hdfs")
'RefreshUserToGroupsMappingsRequestProto"*
(RefreshUserToGroupsMappingsResponseProto"1
/RefreshSuperUserGroupsConfigurationRequestProto"2
0RefreshSuperUserGroupsConfigurationResponseProto2Ö
"RefreshUserMappingsProtocolServiceŠ
refreshUserToGroupsMappings4.hadoop.hdfs.RefreshUserToGroupsMappingsRequestProto5.hadoop.hdfs.RefreshUserToGroupsMappingsResponseProto¢
#refreshSuperUserGroupsConfiguration<.hadoop.hdfs.RefreshSuperUserGroupsConfigurationRequestProto=.hadoop.hdfs.RefreshSuperUserGroupsConfigurationResponseProtoBP
%org.apache.hadoop.hdfs.protocol.protoB!RefreshUserMappingsProtocolProtosˆ 